### ISSUE TITLE
Request for Support for M5stickC Plus2

### ISSUE THREAD

**Issue by Arbolencio** [dj1ch/minigotchi#125]
I would like to suggest adding support for the M5stickC Plus2 device in the Minigotchi project.
Including M5stickC Plus2 as compatible hardware would significantly enhance the project's capabilities and offer users more configuration options.
The M5stickC Plus2, with its advanced features and compatibility with ESP32, would be a valuable addition to the Minigotchi project. I hope you consider this suggestion and add support for this device.

**Comment by dj1ch** [comment]
Thanks for the request, I will add support for that when I can and I'll let you know.

**Comment by dj1ch** [comment]
@Arbolencio Question, is the ESP32 fork able to compiled on the m5?

**Comment by Arbolencio** [comment]
@dj1ch Yes, the ESP32 fork can be compiled on the M5. The M5Stack uses the ESP32 chip as its main processor, so you can generally use the same code and libraries as for other ESP32 devices.

**Comment by dj1ch** [comment]
> @dj1ch Yes, the ESP32 fork can be compiled on the M5. The M5Stack uses the ESP32 chip as its main processor, so you can generally use the same code and libraries as for other ESP32 devices.

I'm assuming the problem is the screen? This may not be relevant to this repo anyway since this is for the ESP8266 version.

**Comment by Arbolencio** [comment]
@dj1ch Exactly, I think the problem is with the screen since there is no support, as for the request to support the m5stickc plus 2, it could remain as an idea for the future

**Comment by dj1ch** [comment]
> @dj1ch Exactly, I think the problem is with the screen since there is no support, as for the request to support the m5stickc plus 2, it could remain as an idea for the future

I'm in the process of adding support for the cheap yellow display on the ESP32 fork, I will probably do this right after. Mostly community members have helped add screen support, so this process could actually be really fast.

**Comment by Arbolencio** [comment]
> after

Thank you very much for everything, please let me know anything, a hug and good luck, I will support this project with all my heart

**Comment by Arbolencio** [comment]
> after

Thank you very much for everything, please let me know anything, a hug and good luck, I will support this project with all my heart

**Comment by dj1ch** [comment]
> > after
> 
> Thank you very much for everything, please let me know anything, a hug and good luck, I will support this project with all my heart

I will be sure to update this issue on this process, thanks for supporting the project this helps out a lot!

**Comment by dj1ch** [comment]
Someone is currently working on support for the screen. I'll further update you once a PR is made.
