### ISSUE TITLE
Support for wio terminal

### ISSUE THREAD

**Issue by steveiliop56** [dj1ch/minigotchi#131]
Hello!

Awesome project! I would like to suggest an extra board to add to the project, wio terminal! Wio is a small device released by Seeedstudio based on a samd51 chip and a realtek wifi/bluetooth module. The Arduino drivers for it are pretty stable and easy to use. The thing I believe would make this device worth to be added is that it has a 320x240 TFT color screen that would be very fun to display the pawnagotchi faces lol. What do you think? Is it too complicated to add? (I don't know c well enough to add something myself I am mostly a ts/python dev)

**Comment by dj1ch** [comment]
I'm going to have to look into it more. Thank you for the suggestion and I'll get back to you ASAP

**Comment by steveiliop56** [comment]
Coool. Thak you!

**Comment by dj1ch** [comment]
I did a bit of research, and it looks like the documentation to send raw packets is pretty *obscure*, I found a mixture of forum posts and blogs to do this. Probably going to have to make another fork, this requires a different wifi library among other things. I'll look into purchasing a wio terminal for testing.

**Comment by steveiliop56** [comment]
Ohh it's that complex? Well if it's that complex I don't think you should add it lol. It would require a lot of refactoring and probably a fork as you said. Also if you don't have the hardware it's a bit pointless for you... I will close it as not planned. Thank you though!

**Comment by dj1ch** [comment]
> Also if you don't have the hardware it's a bit pointless for you...

Most of the screens and stuff are usually added by additional contributors, I still have a vanilla minigotchi. If you want to test releases, let me know.

**Comment by steveiliop56** [comment]
Well c is not really my strong part lol. I used to write code for Arduino when I was like 10 (we are the same age lol) now I don't remember anything I switched to full stack/python stuff. So I am afraid I can't contribute.

**Comment by dj1ch** [comment]
> Well c is not really my strong part lol.

I meant like having you compile from the development branch on the fork, so you can verify that the minigotchi is working correctly, deauthing, switching wifi channels, etc. You probably won't have to write much C/C++ in this case.

> (we are the same age lol)

That's crazy lmao

**Comment by steveiliop56** [comment]
Yeah I can definitely test. My wio is sitting there collecting dust so that will be a good use for it.

**Comment by dj1ch** [comment]
Cool, I'll add this to my to-do list. Hmu on the pwnagotchi discord server, it'll make testing a little bit easier for me.

**Comment by steveiliop56** [comment]
Can you share the link for the discord server please?

**Comment by dj1ch** [comment]
> Can you share the link for the discord server please?

https://discord.gg/PgaU3Vp

**Comment by steveiliop56** [comment]
Alright I joined.

**Comment by dj1ch** [comment]
> Alright I joined.

Cool, the thread for minigotchi-related stuff is in `pwnrojects`  > `Minigotchi on ESP32/ESP8266`, I'll give you more info there

**Comment by dj1ch** [comment]
Just recently got my Wio terminal and I am working on porting it. I'll let you know how it goes. Repo is https://github.com/dj1ch/minigotchi-wio-terminal, I haven't done much yet.

**Comment by steveiliop56** [comment]
Oh wow niceee

**Comment by dj1ch** [comment]
Tbh I can see why your Wio terminal has been collecting dust. Making projects for it is such a pain, and there's literally nothing interesting made for the Wio terminal as far as I can see.

**Comment by dj1ch** [comment]
@steveiliop56 Lately I haven't found much information on how to get the Wio terminal to do things like sniffing or raw packet sending. The Wifi-related libraries for the Wio terminal can only do basic stuff(ex: connecting to Wifi), there are other SDKs for the RTL8720DN but it turns out there are specific microcontrollers that use that chip, not only the Wio terminal which isn't meant to use that SDK. The packet injection and that one wifi sniffing example we did look at recently used that SDK,  which I thought would be compatible with the Wio terminal but isn't unfortunately. For now, I might have to close this issue and archive the Wio terminal repository, I'm sorry for the inconvenience.

**Comment by steveiliop56** [comment]
No problem! It's mostly seeed's fault for making a product then abandoning it, thank you for trying though!
