### ISSUE TITLE
How about support for this lil guy NodeMCU ESP8266 Development Board with 0.96 Inch OLED Display

### ISSUE THREAD

**Issue by dj1ch** [dj1ch/minigotchi#133]
### Discussed in https://github.com/dj1ch/minigotchi/discussions/132

<div type='discussions-op-text'>

<sup>Originally posted by **DSCustoms** June  4, 2024</sup>
Not to add more work, I'm not sure exactly what would need to be changed, I've tried a few things and the minigotchi is running but I can't get this display to work. 

https://www.amazon.com/dp/B0BVM3H46B?psc=1

It's a great little board with the oled already onboard, but it needs this u8g2 library and commands.

https://github.com/olikraus/u8g2/wiki

https://kbin.social/m/Arduino/t/779187/Default-setup-and-screen-display-code-for-Ideaspark-ESP8266-096OLED

Anyone want to tackle this or give me a little idea what to start to change? </div>

**Comment by matrix224** [comment]
Not sure if you had issues with the display in general or just on the minigotchi, but I have the display working in general using a small program:

```
#include <U8g2lib.h>
#include <Arduino.h>
#include <Wire.h>

U8G2_SSD1306_128X64_NONAME_F_SW_I2C u8g2(U8G2_R0, 14, 12, U8X8_PIN_NONE);
int num = 0;

void setup() {
  Serial.begin(115200);
  if (!u8g2.begin()) {
    delay(10000);
    Serial.println("Failed to begin");
    for(;;);
  }
  u8g2.setFont(u8g2_font_7x14B_tr);
}

void loop() {
  u8g2.clearBuffer();
  u8g2.drawStr(0, 10, "Hello there!");
  u8g2.setDrawColor(1);
  if (++num%2 == 0) {
      u8g2.drawStr(0, 30, ">.>");
  } else {
      u8g2.drawStr(0, 30, "<.<");
  }
  u8g2.sendBuffer();
  delay(1000);
}
```

I can help play around with putting it into the minigotchi later if I get time, but wanted to throw this here regardless in case it's useful to you.

**Comment by dj1ch** [comment]
> Not sure if you had issues with the display in general or just on the minigotchi, but I have the display working in general using a small program:
> 
> ```
> #include <U8g2lib.h>
> #include <Arduino.h>
> #include <Wire.h>
> 
> U8G2_SSD1306_128X64_NONAME_F_SW_I2C u8g2(U8G2_R0, 14, 12, U8X8_PIN_NONE);
> int num = 0;
> 
> void setup() {
>   Serial.begin(115200);
>   if (!u8g2.begin()) {
>     delay(10000);
>     Serial.println("Failed to begin");
>     for(;;);
>   }
>   u8g2.setFont(u8g2_font_7x14B_tr);
> }
> 
> void loop() {
>   u8g2.clearBuffer();
>   u8g2.drawStr(0, 10, "Hello there!");
>   u8g2.setDrawColor(1);
>   if (++num%2 == 0) {
>       u8g2.drawStr(0, 30, ">.>");
>   } else {
>       u8g2.drawStr(0, 30, "<.<");
>   }
>   u8g2.sendBuffer();
>   delay(1000);
> }
> ```
> 
> I can help play around with putting it into the minigotchi later if I get time, but wanted to throw this here regardless in case it's useful to you.

I haven't had the chance to get to it yet, it could be a simple addition to `display.cpp` from the look of that

**Comment by matrix224** [comment]
Yeah I actually played with it a little more and have it working on the minigotchi.
Two things though:

1. The text doesn't wrap like with the Adafruit one. I didn't see any obvious way to enable or do this, so it would probably have to be something written ourselves to handle it.
2. This is the only display I've used so far, so I can't do a comparison of this vs other displays. However, when this display is on, it kind of runs noticeably slower. It hits around 2.5 advertisement packets/second with the screen enabled, vs 9+ headless. Maybe that's just a general thing with any display enabled though? The deauth packets are only 2.5/s with the screen vs 4.8 or so headless too, which is much slower regardless than my other NodeMCU board I've been using which consistently is at 9+. So I dunno what's going on in general there.

**Comment by dj1ch** [comment]
> The text doesn't wrap like with the Adafruit one. I didn't see any obvious way to enable or do this, so it would probably have to be something written ourselves to handle it.

Can you send a screenshot perhaps? I think we can do something like add spaces or make an extra line if the the dialogue that the minigotchi says is beyond the screen size

> This is the only display I've used so far, so I can't do a comparison of this vs other displays. However, when this display is on, it kind of runs noticeably slower. It hits around 2.5 advertisement packets/second with the screen enabled, vs 9+ headless. Maybe that's just a general thing with any display enabled though? The deauth packets are only 2.5/s with the screen vs 4.8 or so headless too, which is much slower regardless than my other NodeMCU board I've been using which consistently is at 9+. So I dunno what's going on in general there.

Generally, I think it's a lot slower with any display. fastest I've seen was with an ESP32 with around 6~7 pkt/s

**Comment by matrix224** [comment]
> Can you send a screenshot perhaps? I think we can do something like add spaces or make an extra line if the the dialogue that the minigotchi says is beyond the screen width

Yeah I already wrote something to handle it all and break it into several lines. I'll get pictures to show before/after when I'm home later.


> Generally, I think it's a lot slower with any display. fastest I've seen was with an ESP32 with around 6~7 pkt/s

Alright I was guessing that was the case. 
On a similar note, I haven't seen any videos of the SD1306, just pictures. When the screen updates there, does it kind of flash the text as it changes, or does it smoothly update it all in one go? (Kind of hard to describe but I'll just show you later if it's not clear).
For the u8g2 stuff, it's seemed like I need to wait until the small text method is called before actually updating the screen to make it all change smoothly. Otherwise if I update the screen in both the face method and small text method, the text kind of looks like it flashes as it changes.

**Comment by matrix224** [comment]
> > Can you send a screenshot perhaps? I think we can do something like add spaces or make an extra line if the the dialogue that the minigotchi says is beyond the screen width
> 
> Yeah I already wrote something to handle it all and break it into several lines. I'll get pictures to show before/after when I'm home later.
> 

Without any linebreaking:
![20240611_074638](https://github.com/dj1ch/minigotchi/assets/3128369/b9322dac-b866-4b36-8266-32d7c6fd2e4d)

With line breaking:
![20240611_074520](https://github.com/dj1ch/minigotchi/assets/3128369/88449c6f-14fc-4e96-805f-f6f7a4195470)

**Comment by matrix224** [comment]
> Alright I was guessing that was the case. On a similar note, I haven't seen any videos of the SD1306, just pictures. When the screen updates there, does it kind of flash the text as it changes, or does it smoothly update it all in one go? (Kind of hard to describe but I'll just show you later if it's not clear).

I realized I actually had some SSD1306 left over from earlier projects so I dug them out to see. It looks like it does flash too:


https://github.com/dj1ch/minigotchi/assets/3128369/e1ed0744-800a-4724-94bf-33cc8ac8d6b9


If you update cleanDisplayFace() though to not call display() on the adapter and instead only call it in attachSmallText(), it updates much more smoothly and I think also is slightly better performance since you're not drawing the whole screen twice in quick succession:


https://github.com/dj1ch/minigotchi/assets/3128369/ce84df1c-3e9e-4dc5-a777-1cd2ce6f9369

**Comment by dj1ch** [comment]
> > Alright I was guessing that was the case. On a similar note, I haven't seen any videos of the SD1306, just pictures. When the screen updates there, does it kind of flash the text as it changes, or does it smoothly update it all in one go? (Kind of hard to describe but I'll just show you later if it's not clear).
> 
> I realized I actually had some SSD1306 left over from earlier projects so I dug them out to see. It looks like it does flash too:
> 
>  20240611_133759.mp4 
> If you update cleanDisplayFace() though to not call display() on the adapter and instead only call it in attachSmallText(), it updates much more smoothly and I think also is slightly better performance since you're not drawing the whole screen twice in quick succession:
> 
>  20240611_133910.mp4 
> The downside here of course is that if you wanted to update just the face anywhere, you wouldn't be able to without also calling attachSmallText(). Maybe it could just be a single method that takes a face and optional text to attach instead of two different methods

yeah, looks like this is totally possible. As for the u8g2 changes we could probably do the same thing for that, the line-breaking looks to be very helpful.
