### ISSUE TITLE
error in function `ieee80211_raw_frame_sanity_check'

### ISSUE THREAD

**Issue by 19Bender83** [dj1ch/minigotchi#160]
Hi

I tried to compile the code for my M5Cardputer but got an error "multiple definition of ieee80211_raw_frame_sanity_check'" (output shorted) because it was also defined in the library of espressif.
My workaround was to instruct the linker to do weak linking. What i did to get the code compiled was very easy:
from `extern "C" int ieee80211_raw_frame_sanity_check(int32_t arg, int32_t arg2,
                                                int32_t arg3) {
  return 0;
}`
to `extern "C" int __attribute__((weak)) ieee80211_raw_frame_sanity_check(int32_t arg, int32_t arg2,
                                                int32_t arg3) {
  return 0;
}`
okay not the best way but its working for me.

I know there are also other workarounds out there for other projcets but i think this is even better then to hexedit a library

**Comment by dj1ch** [comment]
> Hi
> 
> I tried to compile the code for my M5Cardputer but got an error "multiple definition of ieee80211_raw_frame_sanity_check'" (output shorted) because it was also defined in the library of espressif. My workaround was to instruct the linker to do weak linking. What i did to get the code compiled was very easy: from `extern "C" int ieee80211_raw_frame_sanity_check(int32_t arg, int32_t arg2, int32_t arg3) { return 0; }` to `extern "C" int __attribute__((weak)) ieee80211_raw_frame_sanity_check(int32_t arg, int32_t arg2, int32_t arg3) { return 0; }` okay not the best way but its working for me.
> 
> I know there are also other workarounds out there for other projcets but i think this is even better then to hexedit a library

just to make sure, you did the edits to the `platforms.txt` as mentioned in the ESP32 install guide? the development branch right now is still in the progress of fixing a bunch of issues.

**Comment by 19Bender83** [comment]
Thanks for the fast reply.... ehm sorry dont know if I'm to stupid but there is no reference to the platforms.txt in the install guide. Do you mean the config.cpp?
I give it another try with the release instead the dev branch, did not had the time to look at the changes between dev branch and release.
My C/C++ knowledge is not the best but I give my best and will be happy if I could support you I any way, just pn me.
Regards

**Comment by dj1ch** [comment]
> Thanks for the fast reply.... ehm sorry dont know if I'm to stupid but there is no reference to the platforms.txt in the install guide. Do you mean the config.cpp?

you'll need to go to the ESP32 fork for the ESP32 install guide, the install guide for the ESP8266 isn't the same.

Link: https://github.com/dj1ch/minigotchi-ESP32/blob/main/INSTALL.md

**Comment by 19Bender83** [comment]
Thanks a lot for the hint

**Comment by dj1ch** [comment]
no problem, let me know how the installation works out. and correction, it wasn't `platforms.txt`, it was `platform.txt` instead.
