### ISSUE TITLE
Pwnagotchi scan delay

### ISSUE THREAD

**Issue by matrix224** [dj1ch/minigotchi#162]
I'm not sure if I'm overlooking something, but in `Pwnagotchi::detect()` shouldn't there be some kind of delay after calling `Minigotchi::monStart()`? Otherwise isn't it just basically starting and stopping the scan almost instantly without giving it any time to actually detect something?
I'm guessing maybe it was meant to be put before the whole scanning loop above it, or at least before the long delay that's at the end of it. If it's supposed to go before the loop above it then I would opt to also remove the `if (!Config::parasite) {` since I had put that in under the impression that the loop was just for show, not functionally doing anything.

**Comment by dj1ch** [comment]
This is mostly just for show

```cpp
      Serial.println("(0-o) Scanning for Pwnagotchi.");
      Display::updateDisplay("(0-o)", "Scanning  for Pwnagotchi.");
      delay(Config::shortDelay);
      Serial.println("(o-0) Scanning for Pwnagotchi..");
      Display::updateDisplay("(o-0)", "Scanning  for Pwnagotchi..");
      delay(Config::shortDelay);
      Serial.println("(0-o) Scanning for Pwnagotchi...");
      Display::updateDisplay("(0-o)", "Scanning  for Pwnagotchi...");
      delay(Config::shortDelay);
      Serial.println(" ");
      delay(Config::shortDelay);
```

I placed the long delay after to give it time to scan so that makes sense. 

However, I placed a conditional after using a callback to essentially have it scan immediately which could lead to the logic issue. I could probably just place the callback initialization before the for loop

**Comment by dj1ch** [comment]
> However, I placed a conditional after using a callback to essentially have it scan immediately which could lead to the logic issue. I could probably just place the callback initialization before the for loop

just did that here in [pwnagotchi.cpp](https://github.com/dj1ch/minigotchi/blob/development/minigotchi/pwnagotchi.cpp#L39) on either version

**Comment by matrix224** [comment]
Cool, thank you for taking a look at it!
I'll mark this closed
