### ISSUE TITLE
SH1106 support request

### ISSUE THREAD

**Issue by DSCustoms** [dj1ch/minigotchi#165]
I thought that the SH1106 screens would either be plug and play or work very easily, but I haven't been able to get it to work myself. Do you think you could add support for the SH1106 screens when you get a chance? There's a nice 1.3" screen which would be great for handhelds. 

1.3 Inch I2C OLED Display Module 128x64 Pixel SH1106 Screen Module

It connects and lights up, but only shows static right now. There is an adafruit SH110X library that should cover it, I also found this repo 
https://github.com/fcgdam/Adafruit_SH1106

Thanks!

**Comment by dj1ch** [comment]
the process might take a minute, but ill see what I can do from here. i saw a couple of arduino repos out there so it shouldn't be that hard.

**Comment by DSCustoms** [comment]
That would be great. Wish I could help more on software but I’m a hardware and design guy 😂

**Comment by dj1ch** [comment]
by the way, do you have that display? if possible, can you test the building from the development branch to see if the changes I make are compatible with your display(once I make them ofc)?

**Comment by DSCustoms** [comment]
> by the way, do you have that display? if possible, can you test the building from the development branch to see if the changes I make are compatible with your display(once I make them ofc)?

Yeah I've got a bunch of the screens and a brand new design to use them with! 
![Minigotchis](https://github.com/dj1ch/minigotchi/assets/40194310/9e971c8f-8048-40a0-82dd-6b66f7f22236)

**Comment by DSCustoms** [comment]
https://github.com/dj1ch/minigotchi/assets/40194310/ce2fe94b-c88b-4f16-a900-3f8d17027dd0

**Comment by dj1ch** [comment]
I haven't got the time to get to this issue... yet. There's another issue that needs to be dealt with regarding pwnagotchi scanning in case you need to know. I can try making the fix for the ESP8266 sometime today or tomorrow.

**Comment by DSCustoms** [comment]
Oh I’m not posting to harass you 😂 just showing some motivational pictures for the community.  I’ve got other uses for these things too, just threw this together for the mini G.

**Comment by dj1ch** [comment]
I just recently started working on the project again. Have you made any progress so far on your end?

**Comment by dj1ch** [comment]
@DSCustoms Are you able to test the latest from the development branch (ESP8266)?

**Comment by DSCustoms** [comment]
Yes I can test. I’ll go look at the changes. Thanks!

**Comment by DSCustoms** [comment]
Fired right up! All I tested was the screen, I didn't dig into the parasite mode or anything else that is new yet, but the SH1106 screen works.  I did have to change the pin assignments, are you using a different 8266 board I'm not familiar with? These are the standard GPIOs for all the ones I have and have seen.
#define SH1106_SCL 5
#define SH1106_SDA 4

Let me know if anything else needs hardware testing! Thanks for putting this together

![IMG_5797](https://github.com/user-attachments/assets/9d3fdf43-da7e-48d3-93ba-8384fcb6837c)

**Comment by dj1ch** [comment]
> Fired right up! All I tested was the screen, I didn't dig into the parasite mode or anything else that is new yet, but the SH1106 screen works. I did have to change the pin assignments, are you using a different 8266 board I'm not familiar with? These are the standard GPIOs for all the ones I have and have seen. #define SH1106_SCL 5 #define SH1106_SDA 4
> 
> Let me know if anything else needs hardware testing! Thanks for putting this together
> 
> ![IMG_5797](https://private-user-images.githubusercontent.com/40194310/350387031-9d3fdf43-da7e-48d3-93ba-8384fcb6837c.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzOTc5NzEsIm5iZiI6MTcyMTM5NzY3MSwicGF0aCI6Ii80MDE5NDMxMC8zNTAzODcwMzEtOWQzZmRmNDMtZGE3ZS00OGQzLTkzYmEtODM4NGZjYjY4MzdjLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDE0MDExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNDU0ZDJlOTYwMzJmMjA2NjNjMDdhMmYzYzJhY2U2ZWVkMGZjOTQ0MDQ1Zjg4NDNkOTI1NDkyOTg4YmI2NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bscsxmBuQSuSPoW3h9Qp79qtTisPASyOvaBlQokedaU)

Yeah, I just put in the default, I wasn't fully aware of what pins to use. Thanks for the fix, I'll incorporate this. For now I don't think there will be any more screen testing (at least until the following release.)

**Comment by dj1ch** [comment]
Just added your fixes in:

```cpp
#define SH1106_SCL 5
#define SH1106_SDA 4
```

Thank you for the help!
